template-file-path: ./templates/ecs-stack.yaml

parameters:
  ProjectName: ecs-cicd
  NetworkStackName: ecs-infrastructure-network
  SecurityStackName: ecs-infrastructure-security
  AlbStackName: ecs-infrastructure-alb
  EcrRepositoryName: helloapp
  ImageTag: Bruce_Mutsinzi_helloapp-2f4c031 
  ContainerPort: 8080
  TaskCpu: '512'
  TaskMemory: '1024'
  DesiredCount: 1

tags:
  Project: ecs-cicd
  ManagedBy: GitSync
  Stack: ecs
  Module: containers-aws