template-file-path: ./templates/security-stack.yaml

parameters:
  ProjectName: ecs-cicd
  NetworkStackName: ecs-infrastructure-network
  ContainerPort: 8080

tags:
  Project: ecs-cicd
  ManagedBy: GitSync
  Stack: security
  Module: containers-aws