template-file-path: ./parent-stack.yaml

parameters:
  ProjectName: ecs-cicd
  TemplateBucketName: 842676015206-ecs-cicd-templates
  EcrImageTag: latest

tags:
  Project: ecs-cicd
  ManagedBy: GitSync
  Architecture: nested
  Module: containers-aws