template-file-path: ./templates/pipeline-stack.yaml

parameters:
  ProjectName: ecs-cicd
  EcrRepositoryName: helloapp
  AppRepoOwner: Bruce-the-dev
  AppRepoName: ecs_ci-cd_lab
  AppRepoBranch: main
  CodeStarConnectionArn: arn:aws:codeconnections:eu-west-1:842676015206:connection/7afc6488-58d1-4d86-acbd-4befa2f07bdd

tags:
  Project: ecs-cicd
  ManagedBy: GitSync
  Stack: pipeline
  Module: containers-aws