template-file-path: parent-stack.yaml
parameters:
  AppRepoOwner: Bruce-the-dev
  ProjectName: ecs-cicd
  AppRepoName: ecs_ci-cd_lab
  AppRepoBranch: main
  CodeStarConnectionArn: >-
    arn:aws:codeconnections:eu-west-1:842676015206:connection/7afc6488-58d1-4d86-acbd-4befa2f07bdd
  EcrRepositoryName: ecs-cicd-app
tags:
  Project: ecs-cicd
  ManagedBy: GitSync
  Architecture: nested
  Module: containers-aws
